SP-5018-asg-execute-command
stackpulse/playbooks pull request #48
Opened 2021-03-08 16:07 UTC by talbe

## Description

## Best Practices checklist

### General
- [ ] Go over texts with @stackpulse/product
- [ ] Explicitly discuss the _playbook name_, _image_ and _badges_
- [ ] Explicitly consider various _benefits_. As a rule of thumb, there should be 2-3 of them
- [ ] If the playbook has Slack outputs use the Slack experience template

### New playbooks
- [ ] Tested Playbook in a production tenant
- [ ] Added a link in the [README.MD](https://github.com/stackpulse/playbooks/blob/master/README.md)

### Playbook structure
- [ ] For improved human-readability, please add a new empty line between the steps
- [ ] Please add a one-liner comment block before each step, for example: `# Retrieve long connections from the database server`
- [ ] When considering step IDs, please use short, but descriptive terms, explaining what is being done, such as `retrieve_connections_data` or `update_storage_size`
- [ ] When writing params descriptions, start with a capital letter and phrase as a short sentence, such as `User name for database connection` or `Address of the database cluster`

## Screenshot

2021-03-09 11:44 UTC, hagaishapira commented on aws/asg-execute-command/README.md
> +This playbook execute command for given AWS Auto Scaling Group and and verify it's health
```suggestion
This playbook executes a command on each instance of an AWS Auto Scaling Group and and then verifies its health.
```

2021-03-09 12:36 UTC, hagaishapira commented on aws/asg-execute-command/playbook.yaml
> +  description: "Execute command for given AWS Auto Scaling Group and and verify it's health"
```suggestion
  description: "Execute a command on all instances of an AWS Auto Scaling Group and and verify its health"
```

2021-03-09 12:40 UTC, hagaishapira commented
@talbe Also please look at the new graphics guidelines, you need to use the template Lihi created and place the outputs there. Please reach out to her if you're having trouble with it.

2021-03-10 13:37 UTC, talbe commented
@hagaishapira Done

2021-03-10 13:54 UTC, hagaishapira commented on aws/asg-execute-command/playbook.yaml
> +            autoscaling group {{ $.query_chosen_autoscaling_group.AutoScalingGroups[0].AutoScalingGroupName }} is healthy and ready for operation
give a meaningful name to the snippet

2021-03-10 13:56 UTC, hagaishapira requested changes
Please make the parameters view look more refine, use headings, use light mode like we've said. 
![image](https://user-images.githubusercontent.com/29172759/110640075-19fee480-81b9-11eb-9f09-4b8f4830c507.png)

2021-03-10 13:56 UTC, hagaishapira commented on aws/asg-execute-command/playbook.yaml
> +          CONTENT: >
give a meaningful name to the snippet

2021-03-14 15:23 UTC, hagaishapira approved these changes

2021-03-14 15:25 UTC, merged