[SP-5255] Create Incident refinements
stackpulse/playbooks pull request #49
Opened 2021-03-15 09:46 UTC by moshebe

2021-03-15 13:34 UTC, hagaishapira requested changes
Like we've discussed we need full parameterization of all items in the context.

2021-03-15 14:13 UTC, moshebe commented on stackpulse/create-incident-war-room-opsgenie/playbook.yaml
> +      TOPIC: "StackPulse War Room Channel for Incident {{ $.event.Name }} ({{ $.event.ID }})\n {{- if $.join_url }} Zoom meeting link - {{ $.join_url }} {{ end }}"
It removes the whitespaces before the go-template expression

2021-03-16 08:47 UTC, hagaishapira reviewed
Please review the parameter descriptions, these really matter as they are what explains to new user what is this parameter and what they should input there.

2021-03-16 08:47 UTC, hagaishapira commented on stackpulse/create-incident-war-room-opsgenie/playbook.yaml
> +    description: The emails of the users that will be invited to the channel (by default, only the incident reporter).
let's be consistent with double, single or no quotes.

2021-03-16 08:47 UTC, hagaishapira commented on stackpulse/create-incident-war-room-opsgenie/playbook.yaml
> +  - name: eventID
This is the incident ID. please think about this playbook like being run by someone who isn't very familiar with the platform, provide good descriptions and not just placeholder stuff.

2021-03-16 08:47 UTC, hagaishapira commented on stackpulse/create-incident-war-room-pagerduty/playbook.yaml
> +  - name: reporter
These descriptions are not verbose and helpful enough, please think of this like someone who is just using this playbook out of the box trying to create a war room for his incident

2021-03-16 08:47 UTC, hagaishapira commented on stackpulse/create-incident-war-room-pagerduty/playbook.yaml
> +  - name: slackOnCaller
I don't think we need this parameter, the use for this is to ask the *reporter* if the page the pagerduty on caller.

2021-03-16 08:55 UTC, moshebe commented on stackpulse/create-incident-war-room-opsgenie/playbook.yaml
> +    description: The emails of the users that will be invited to the channel (by default, only the incident reporter).
I personally prefer no quotes I think it looks cleaner.
But there are cases when we use special characters so we need to wrap it with quotes.
Do you prefer all the textual fields will be wrapped in this case?

2021-03-16 09:03 UTC, hagaishapira commented
I think that in a playbook we are kinda forced to use quotes and that the
backend adds them either way. I know it is prettier without but we need
more consistency.

On Tue, Mar 16, 2021 at 10:55 AM moshebe ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In stackpulse/create-incident-war-room-opsgenie/playbook.yaml
> <https://github.com/stackpulse/playbooks/pull/49#discussion_r594971042>:
>
> >    - name: invitees
>      type: var
> -    description: "The emails of the users that will be invited to the channel (by default, only the incident reporter)."
> +    description: The emails of the users that will be invited to the channel (by default, only the incident reporter).
>
> I personally prefer no quotes I think it looks cleaner.
> But there are cases when we use special characters so we need to wrap it
> with quotes.
> Do you prefer all the textual fields will be wrapped in this case?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/stackpulse/playbooks/pull/49#discussion_r594971042>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG6SIF2Q6MJ3CBMFD3G5P73TD4MJ3ANCNFSM4ZGGNZ4A>
> .
>

2021-03-16 12:01 UTC, hagaishapira approved these changes
Very very nice!

2021-03-16 12:28 UTC, merged