Sp 3732
stackpulse/playbooks pull request #5
Opened 2020-12-22 11:04 UTC by eldadru

2020-12-22 11:19 UTC, rzsp requested changes

2020-12-22 11:19 UTC, rzsp commented on hello-world/hello-world-slack/README.md
> +- Try StackPulse
```suggestion
- Automate your first playbook in StackPulse
```

2020-12-22 11:19 UTC, rzsp commented on hello-world/hello-world-slack/README.md
> +- Understand basic StackPulse terms and usage
```suggestion
- Learn of StackPulse fundamental terms, flow and usage
```

2020-12-22 11:19 UTC, rzsp commented on hello-world/hello-world-slack/README.md
> +- Start creating your own playbooks!
```suggestion
```

2020-12-22 13:05 UTC, hagaishapira commented on hello-world/hello-world-slack/README.md
> +[![Import to StackPulse](../../images/open_in_stackpulse.svg)](https://app.stackpulse.io/playbook/create#https://github.com/stackpulse/playbooks/blob/master/hello-world/hello-world-slack/playbook.yam
should the vendor be `hello-world`? not `stackpulse` and then `hello-world` in it?

2020-12-22 13:05 UTC, hagaishapira commented on hello-world/hello-world-slack/playbook.yaml
> +      MESSAGE_TEXT: "Congratulations!\nYou’ve successfully integrated StackPulse with Slack and triggered your first playbook.\n\nWhat's next?\n\n- Find more <{{ .params.stackpulsePlaybooksURL }}|pla
```suggestion
      MESSAGE_TEXT: "Congratulations!\nYou’ve successfully integrated StackPulse with Slack and triggered your first playbook.\n\nWhat's next?\n\n- Find more <{{ .params.stackpulsePlaybooksURL }}|playbooks> in the StackPulse repository\n- To enrich your automation capabilities, add more <https://app.stackpulse.io/integrations|integrations>\n- Use `/stackpulse help` to see what you can do in Slack\n- For more information, checkout our <https://docs.stackpulse.io|documentation>\n\nWant to know what just happened? check out the <https://app.stackpulse.io/playbook/{{ .metadata.playbookId }}|Trigger & Playbook>"
```

2020-12-22 13:05 UTC, hagaishapira commented on hello-world/hello-world-slack/playbook.yaml
> +  name: hello-world
```suggestion
  name: hello-world-slack
```

2020-12-22 13:05 UTC, hagaishapira commented on hello-world/hello-world-slack/playbook.yaml
> +  - name: stackpulsePlaybooksURL
which url do you mean here? and why does the consumer need to specify it?

2020-12-22 14:17 UTC, eldadru commented on elastic/get-stats/README.md
> -![type](https://img.shields.io/badge/type-triage-green)
We decided to avoid having type for now.

2020-12-22 14:18 UTC, eldadru commented on hello-world/hello-world-slack/playbook.yaml
> +  - name: stackpulsePlaybooksURL
We would like to demonstrate how stackpulse traverse the payload, this will be given from the trigger/alert payload

2020-12-22 14:26 UTC, rzsp requested changes

2020-12-22 14:26 UTC, rzsp commented on hello-world/hello-world-slack/playbook.yaml
> +      MESSAGE_TEXT: "Congratulations!\nYou’ve successfully integrated StackPulse with Slack and triggered your first playbook.\n\nWhat's next?\n\n- Find more <{{ .params.stackpulsePlaybooksURL }}|pla
```suggestion
      MESSAGE_TEXT: "Congratulations!\nYou’ve successfully integrated StackPulse with Slack and triggered your first playbook.\n\nWhat's next?\n\n- Find more <{{ .params.stackpulsePlaybooksURL }}|playbooks> in the StackPulse repository\n- Integrate with all of your cloud stack components <https://app.stackpulse.io/integrations|integrations>\n- Use `/stackpulse help` to see what you can do in Slack\n- For more information, checkout our <https://docs.stackpulse.io|documentation>\n\nWant to know what just happened? check out the <https://app.stackpulse.io/playbook/{{ .metadata.playbookId }}|Trigger & Playbook>"
```

2020-12-22 14:43 UTC, hagaishapira commented on elastic/get-stats/README.md
> -![type](https://img.shields.io/badge/type-triage-green)
So what about removing them from the main README?

2020-12-22 15:10 UTC, eldadru commented on elastic/get-stats/README.md
> -![type](https://img.shields.io/badge/type-triage-green)
Good point, removed as well

2020-12-22 15:10 UTC, eldadru commented on hello-world/hello-world-slack/README.md
> +[![Import to StackPulse](../../images/open_in_stackpulse.svg)](https://app.stackpulse.io/playbook/create#https://github.com/stackpulse/playbooks/blob/master/hello-world/hello-world-slack/playbook.yam
@rzsp - WDYT?

2020-12-27 09:49 UTC, hagaishapira commented on hello-world/hello-world-slack/README.md
> +[![Import to StackPulse](../../images/open_in_stackpulse.svg)](https://app.stackpulse.io/playbook/create#https://github.com/stackpulse/playbooks/blob/master/hello-world/hello-world-slack/playbook.yam
@eldadru did you decide on this?
still think should be under stackpulse vendor

2020-12-27 09:50 UTC, hagaishapira approved these changes
LGTM. see 1 open comment

2020-12-27 10:06 UTC, merged