simple-kubernetes-playbooks
stackpulse/playbooks pull request #56
Opened 2021-04-18 14:51 UTC by talbe

## Description

## Best Practices checklist

### General
- [ ] Go over texts with @stackpulse/product
- [ ] Explicitly discuss the _playbook name_, _image_ and _badges_
- [ ] Explicitly consider various _benefits_. As a rule of thumb, there should be 2-3 of them
- [ ] If the playbook has Slack outputs use the Slack experience template

### New playbooks
- [ ] Tested Playbook in a production tenant
- [ ] Added a link in the [README.MD](https://github.com/stackpulse/playbooks/blob/master/README.md)

### Playbook structure
- [ ] For improved human-readability, please add a new empty line between the steps
- [ ] Please add a one-liner comment block before each step, for example: `# Retrieve long connections from the database server`
- [ ] When considering step IDs, please use short, but descriptive terms, explaining what is being done, such as `retrieve_connections_data` or `update_storage_size`
- [ ] When writing params descriptions, start with a capital letter and phrase as a short sentence, such as `User name for database connection` or `Address of the database cluster`

## Screenshot

2021-04-19 07:15 UTC, hagaishapira reviewed
In general we need more extensive descriptions on the playbooks themselves

2021-04-19 07:15 UTC, hagaishapira commented on kubernetes/delete-pod/playbook.yaml
> +  description: Kubernetes rollout restart
Wrong description

2021-04-19 07:15 UTC, hagaishapira commented on kubernetes/delete-pod/README.md
> +This playbook performs pod deletion
Please keep the how to get started in all READMEs

2021-04-19 07:15 UTC, hagaishapira commented on kubernetes/label-logs/playbook.yaml
> +  description: Kubernetes label logs
The descriptions should be a bit more explanatory of what this playbook is doing

2021-04-19 07:16 UTC, hagaishapira commented on kubernetes/label-logs/README.md
> +# Kubernetes Fetch Logs by Label
I would change the path to be "logs-by-label" as it's clearer than "label-logs"

2021-04-19 07:16 UTC, hagaishapira commented on kubernetes/label-logs/README.md
> +This playbook fetch logs by label
```suggestion
This playbook fetches logs by label
```

2021-04-19 07:19 UTC, hagaishapira requested changes
We need all of these to output their content somewhere. 
Please add slack with either the logs, or confirmation for the rollout / pod deletion

2021-04-20 07:39 UTC, hagaishapira commented on kubernetes/delete-pod/playbook.yaml
> +      RESOURCE_TYPE: "pod"
What about the more advanced grace parameters?

2021-04-20 07:44 UTC, hagaishapira requested changes
What about the Slack steps to send over the outputs?

2021-04-20 07:44 UTC, hagaishapira commented on kubernetes/delete-pod/README.md
> +4. Connect it to monitoring alerts or execute manually
What about 3?

2021-04-20 07:44 UTC, hagaishapira commented on kubernetes/delete-pod/README.md
> +This playbook performs pod deletion
This text is a bit laconic. Please Change this and the other to be more expressive. 
i.e. "This playbook allows you to delete a forcefully delete a pod without any grace period. This enables you to delete even stuck or hanging pods."

2021-04-20 07:44 UTC, hagaishapira commented on kubernetes/rollout-restart/README.md
> +4. Connect it to monitoring alerts or execute manually
What about 3?

2021-04-20 07:44 UTC, hagaishapira commented on kubernetes/logs/README.md
> +4. Connect it to monitoring alerts or execute manually
What about 3?

2021-04-20 07:44 UTC, hagaishapira commented on kubernetes/logs-by-label/README.md
> +4. Connect it to monitoring alerts or execute manually
What about 3?

2021-04-20 07:44 UTC, hagaishapira commented on kubernetes/rollout-restart/README.md
> +This playbook performs rollout restart for given kubernetes entity
```suggestion
This playbook performs rollout restart for a given Kubernetes deployment.
```

2021-04-28 07:09 UTC, hagaishapira commented on kubernetes/delete-pod/README.md
> +This playbook allows you to delete forcefully a pod without any grace period. This enables you to delete even stuck or hanging pods.
```suggestion
This playbook allows you to forcefully delete a pod without any grace period. This enables you to delete even stuck or hanging pods.
```

2021-04-28 07:25 UTC, hagaishapira requested changes
See comments and suggestions

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/delete-pod/playbook.yaml
> +    description: whether
missing description

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/delete-pod/playbook.yaml
> +    description: The relevant namespace to operate
```suggestion
    description: The namespace of the pod we wish to delete
    default: default
```

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/delete-pod/playbook.yaml
> +    description: The relevant entity to operate on
if this is delete pod then what does entity mean? This should be podName or pod with the description saying that this should be a name

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/delete-pod/playbook.yaml
> +    description: The recipient for the playbook result notification
add a default of "{{ $.metadata.userEmail }}"

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/delete-pod/playbook.yaml
> +      CONTENT: "The request to delete the entity {{ $.params.entity}} ended with the result {{ $.kubectl_cmd }} "
```suggestion
      CONTENT: "The request to delete the pod {{ $.params.entity}} ended with the result {{ $.kubectl_cmd }} "
```

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/logs-by-label/README.md
> +This playbook allows you to fetch logs by given label
```suggestion
This playbook allows you to fetch logs by a given label.
For example, getting logs from all pods with the label `app=mysql`.
```

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/logs-by-label/playbook.yaml
> +    example: "default"
Do we have example for params?

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/logs-by-label/playbook.yaml
> +    example: "default"
I don't think so

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/logs-by-label/playbook.yaml
> +    required: false
I don't think we have required too

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/logs-by-label/playbook.yaml
> +    required: false
We do have optional, but if you use that make sure the playbook actually handles that gracefully

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/logs-by-label/playbook.yaml
> +    description: The relevant entity to operate on
Fix description for label

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/logs/playbook.yaml
> +    example: "default"
again go over all of these as we don't have examples and required in parameters

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/logs/playbook.yaml
> +  - name: allContainers
What do we expect users to input here? what's the default?

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/rollout-restart/playbook.yaml
> +    description: The relevant namespace to operate
```suggestion
    description: The relevant namespace to operate in
```

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/rollout-restart/playbook.yaml
> +    description: The relevant namespace to operate
either user optional if that works gracefully or have a `default: default`

2021-04-28 07:25 UTC, hagaishapira commented on kubernetes/rollout-restart/playbook.yaml
> +    description: The relevant entity to operate on
```suggestion
    description: The relevant entity to operate on, ie. `deployment/nginx`.
```

2021-04-28 08:02 UTC, talbe commented on kubernetes/delete-pod/playbook.yaml
> +    description: The relevant entity to operate on
kubectl delete command can delete not only pods.. you can delete services for example.. actually any kubernetes entity

2021-04-28 08:03 UTC, talbe commented on kubernetes/delete-pod/playbook.yaml
> +    description: The relevant entity to operate on
NVM 
this is delete pod playbook
will update

2021-04-28 08:06 UTC, talbe commented on kubernetes/logs-by-label/playbook.yaml
> +    example: "default"
no we don't

2021-04-28 08:08 UTC, talbe commented on kubernetes/logs-by-label/playbook.yaml
> +    required: false
I will set as required

2021-04-28 08:09 UTC, talbe commented on kubernetes/logs/playbook.yaml
> +  - name: allContainers
boolean value
will add default

2021-04-28 08:53 UTC, hagaishapira commented on kubernetes/delete-pod/playbook.yaml
> +    description: deletes pod without any grace period.
What should the user input here? This is free text, we don't have a bool type parameter

2021-04-28 08:53 UTC, hagaishapira commented on kubernetes/delete-pod/playbook.yaml
> +  - name: entity
```suggestion
  - name: pod
```

2021-04-28 08:57 UTC, hagaishapira requested changes

2021-04-28 08:57 UTC, hagaishapira commented on kubernetes/logs-by-label/playbook.yaml
> +    required: false
but we don't have required, by default everything is required. We only have optional to set as "non required"

2021-04-28 08:57 UTC, hagaishapira commented on kubernetes/logs/playbook.yaml
> +    description: Whether fetch logs for all containers (--all-containers flag).
In general when you have free text for parameters that should actually be boolean please specify in the description, "must be either `true` or `false`"

2021-04-28 08:57 UTC, hagaishapira commented on kubernetes/rollout-restart/playbook.yaml
> +    description: The relevant namespace to operate in, ie. `deployment/nginx`.
```suggestion
    description: The relevant namespace to operate in.
    default: default
```

2021-04-28 13:32 UTC, hagaishapira approved these changes
Merge latest comments

2021-04-28 13:32 UTC, hagaishapira commented on kubernetes/delete-pod/playbook.yaml
> +    description: deletes pod without any grace period. must be either true or false.
```suggestion
    description: Deletes pod without any grace period. Must be either `true` or `false`.
```

2021-04-28 13:32 UTC, hagaishapira commented on kubernetes/logs-by-label/playbook.yaml
> +    description: The relevant label to filter by
```suggestion
    description: The relevant label to filter by (for example `app=mysql`).
```

2021-04-28 13:32 UTC, hagaishapira commented on kubernetes/logs/playbook.yaml
> +    description: Whether fetch logs for all containers (--all-containers flag). must be either true or false.
```suggestion
    description: Whether fetch logs for all containers (--all-containers flag). Must be either `true` or `false`.
```

2021-04-28 13:32 UTC, hagaishapira commented on kubernetes/logs/README.md
> +This playbook allows you to fetch logs from kubernetes entity, with all the options that kubernetes expose to you.
```suggestion
This playbook allows you to fetch logs from a Kubernetes entity, with all the options that Kubernetes expose to you.
```

2021-04-28 13:32 UTC, hagaishapira commented on kubernetes/logs/playbook.yaml
> +    description: The relevant entity to operate on
```suggestion
    description: The relevant entity to operate on. If the entity (pod or job) has multiple containers, consider using `allContainers: true` 
```

2021-04-28 15:32 UTC, merged