SP-4013: Job failed playbook
stackpulse/playbooks pull request #8
Opened 2021-01-03 12:22 UTC by vic3lord

2021-01-04 09:45 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +            RECIPIENTS: "{{ .params.recipient }}"
```suggestion
            RECIPIENTS: "{{ $.params.recipient }}"
```

2021-01-04 09:45 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +            CONTENT: "{{ .output }}"
```suggestion
            CONTENT: "{{ $.output }}"
```

2021-01-04 09:46 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +  - when: '{{ eq .slack_response "yes" }}'
```suggestion
  - when: '{{ eq $.slack_response "yes" }}'
```

2021-01-04 09:47 UTC, alongat commented on kubernetes/job-failed/README.md
> +This playbook will help you extract the logs from a failed job and help you optionally delete it once you understand the root cause.
Looks like a long sentence, please send the texts through product

2021-01-04 09:48 UTC, vic3lord commented on kubernetes/job-failed/README.md
> +This playbook will help you extract the logs from a failed job and help you optionally delete it once you understand the root cause.
Sure thing

2021-01-04 09:50 UTC, alongat approved these changes
Please ask @rzsp to go over the text

2021-01-04 12:03 UTC, eldadru commented on kubernetes/job-failed/playbook.yaml
> +  - name: gcr.io/stackpulse/steps/slack/send_interactive_message
This is the old step, please upgrade to use the new one (gcr.io aren't supported anymore)

2021-01-04 12:04 UTC, rzsp requested changes

2021-01-06 08:35 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +      SP_REDIRECT_URL: https://app.stackpulse.io/execution/{{ .execution.id }}
```suggestion
      SP_REDIRECT_URL: {{ $.metadata.executionUrl }}
```

2021-01-06 08:35 UTC, vic3lord commented on kubernetes/job-failed/playbook.yaml
> +  - name: gcr.io/stackpulse/steps/slack/send_interactive_message
```suggestion
  - name: us-docker.pkg.dev/stackpulse/public/slack/message/interactive
```

2021-01-06 08:35 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +            SP_REDIRECT_URL: https://app.stackpulse.io/execution/{{ .execution.id }}
```suggestion
           SP_REDIRECT_URL: {{ $.metadata.executionUrl }}
```

2021-01-06 08:37 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +      RESPONSES_JSON: '{"No": "no", "Yes": "yes"}'
I think this changed to No, Yes

2021-01-06 08:38 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +           SP_REDIRECT_URL: {{ $.metadata.executionUrl }}
```suggestion
            SP_REDIRECT_URL: {{ $.metadata.executionUrl }}
```

2021-01-06 08:38 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +            NAMESPACE: '{{ $.params.namespace }}'
```suggestion
            NAMESPACE: "{{ $.params.namespace }}"
```

2021-01-06 08:39 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +            POD_NAME: '{{ .value.name }}'
```suggestion
            POD_NAME: "{{ .value.name }}"
```

2021-01-06 08:39 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +      NAMESPACE: '{{ $.params.namespace }}'
```suggestion
      NAMESPACE: "{{ $.params.namespace }}"
```

2021-01-06 08:39 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +      NAME_CONTAINS: '{{ $.params.job_name }}'
```suggestion
      NAME_CONTAINS: "{{ $.params.job_name }}"
```

2021-01-06 08:40 UTC, alongat requested changes
See small ones

2021-01-06 08:53 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +      RESPONSES_JSON: '{"No": "no", "Yes": "yes"}'
```suggestion
      RESPONSES: "No, Yes"
```

2021-01-06 08:54 UTC, alongat commented on kubernetes/job-failed/playbook.yaml
> +      MESSAGE_TYPE: "BUTTONS_SELECT"
```suggestion
      SELECTOR_TYPE: "BUTTONS_SELECT"
```

2021-01-12 12:46 UTC, alongat approved these changes

2021-01-12 12:47 UTC, merged